# Generated by Django 3.0.8 on 2020-07-13 16:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0005_auto_20181115_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='img_url',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
